apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
    protocol: TCP
